name: Prepare release
on:
  workflow_dispatch:

jobs:
  bump-version:
    name: "Bump version and tag"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up NodeJS environment
        uses: "actions/setup-node@v1"
        with:
          node-version: '18'

      - name: Set up Git environment
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: "Bump version & tag"
        run: npm version patch --message "Bump version to %s"

      - name: Bump v1 branch
        run: git branch -f v1 HEAD

      - name: Push branches
        run: git push origin $GITHUB_REF v1

      - name: Push tag
        run: git push --tags
